@Demo.WebApi.Controllers_HostAddress = http://localhost:5149

GET {{Demo.WebApi.Controllers_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Demo.WebApi.Controllers_HostAddress}}/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "1g234D5678!",
  "firstName": "Daud",
  "lastName": "S.",
  "phoneNumber": "+224 123 456 789"
}

###

POST {{Demo.WebApi.Controllers_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "1g234D5678!",
  "rememberMe": true
}