name: Build

on:
  workflow_call:
    outputs:
      build-path:
        description: "Path to compiled output"
        value: ${{ jobs.build.outputs.build-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.upload.outputs.artifact-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore -o ./build-output

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: ./build-output