name: Publish AspNetCore Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ./src/FluentAnnotationsValidator.AspNetCore/FluentAnnotationsValidator.AspNetCore.csproj

      - name: Build project
        run: dotnet build ./src/FluentAnnotationsValidator.AspNetCore/FluentAnnotationsValidator.AspNetCore.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack ./src/FluentAnnotationsValidator.AspNetCore/FluentAnnotationsValidator.AspNetCore.csproj --configuration Release --output ./nupkg --no-build

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Pack NuGet packages (with symbols, source, and deterministic metadata)
        run: dotnet pack --configuration Release --output ./nupkg --include-symbols --include-source /p:ContinuousIntegrationBuild=true

      - name: Show .NET SDK version
        run: dotnet --info
