name: NuGet Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore FluentAnnotationsValidator.sln

      - name: Build solution projects
        run: dotnet build FluentAnnotationsValidator.sln --configuration Release --no-restore

      - name: Pack NuGet packages (with symbols, source, and deterministic metadata)
        run: dotnet pack src/**/*.csproj --no-restore --configuration Release /p:Version=${{ env.VERSION }} --output ./nupkg --include-symbols --include-source --property:ContinuousIntegrationBuild=true

      - name: Push to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
